
spring:
  application:
    name: eureka-cardService

server:
  port: 8001
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

logging:
   level:
    com:
       example:
         looedu:
           mapper: debug
